# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Bundle application

on:
  push:
    branches:
      - main
      - develop
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Bundle application

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'npm'

    - name: Install NPM dependencies
      run: npm clean-install

    - name: Build application
      run: npm run build

    - name: Publish application as artifact
      uses: actions/upload-artifact@v2
      with:
        name: bundle
        path: dist/*

    - name: Package application for release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd dist/
        tar -czf ../application.tar.gz * .htaccess
        zip -r ../application.zip * .htaccess

    - name: Publish release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          application.tar.gz
          application.zip
